# Site settings
title: A blog about Test Repo
description: A blog about Test Repo
baseurl: "/test-repo" # the subpath of your site, e.g. /blog
#url: "https://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chathuranga Withana
user_description: Chathuranga Withana at Test Repo
user_title: Test Repo
email: chathuwithana@gmail.com
twitter_username: chathuwithana
github_username:  chathuwithana
gplus_username:  chathuwithana
disqus_username: chathuwithana

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
